---
# tasks file for memoryleak.php
- name: Install PHP packages
  package:
    name: "{{ php_install_packages | join(',') }}"
    state: present
  tags:
    - package

- name: Set PHP ini configuration values
  lineinfile:
    line: "{{ item.name + ' = ' + item.value }}"
    path: "{{ php_ini_path }}"
    regexp: "{{ ';?' + item.name + ' =(.*)?'}}"
    state: present
  tags:
    - lininfile
    - php
    - php_ini
  with_items: "{{ php_ini_config }}"

- name: Set PHP FPM configuration values
  lineinfile:
    line: "{{ item.name + ' = ' + item.value }}"
    path: "{{ php_fpm_conf_path }}"
    regexp: "{{ ';?' + item.name + ' =(.*)?'}}"
    state: present
  tags:
    - lininfile
    - php
    - php_fpm_conf
  with_items: "{{ php_fpm_config }}"
  notify: php-fpm-restarted

- name: Create pool files
  template:
    dest: "{{ php_fpm_pool_path }}/{{ item.key }}.conf"
    src: pool.conf.j2
    trim_blocks: true
    force: true
  tags:
    - template
    - php
    - php_fpm_pool
  with_dict: "{{ php_fpm_pool_files }}"
  notify: php-fpm-restarted
