---
# handlers file for memoryleak.php
- name: php-fpm-restarted
  service:
    enabled: "{{ php_fpm_service_enabled }}"
    name: "{{ php_fpm_service_name }}"
    state: restarted
  tags:
    - service
