---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
platforms:
  - name: instance-ubuntu-2004
    image: ubuntu:20.04
    pre_build_image: false

  - name: instance-centos-7
    image: centos:7
    pre_build_image: false

  - name: instance-fedora-33
    image: fedora:33
    pre_build_image: false
provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml

verifier:
  name: ansible
