---
name: Molecule Test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: memoryleak.php

      - name: Test Ansible roles with Molecule
        working-directory: memoryleak.php
        uses: robertdebock/molecule-action@2.6.8
