---
name: Molecule Test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: memoryleak.php

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        working-directory: memoryleak.php
        run: |
          sudo apt install docker
          sudo systemctl start docker
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt

      - name: Test with molecule
        working-directory: memoryleak.php
        run: |
          molecule test
