---
name: Molecule Test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: "memoryleak.php"

      - name: Test Ansible role with Molecule
        uses: robertdebock/molecule-action@2.6.8
        with:
          path: "memoryleak.php"
